# Base Model
## Load Model

In [23]:
import tensorflow as tf
import tensorflow_recommenders as tfrs
#import scann
from dask import dataframe as dd
import os

In [2]:
input_path = "/home/creyesp/tmp/models/model/candidate_model/"
candidate_model = tf.saved_model.load(input_path)
input_path = "/home/creyesp/tmp/models/model/query_model/"
query_model = tf.saved_model.load(input_path)

2022-04-13 11:00:40.604748: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-13 11:00:40.604767: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-13 11:00:40.604781: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (creyesp-peya-uy): /proc/driver/nvidia/version does not exist
2022-04-13 11:00:40.604923: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-13 11:00:40.695629: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLI

In [6]:
query_model([1])

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-0.04756003, -0.03827778,  0.04806868,  0.04033479, -0.04801022,
        -0.03768318,  0.03274133, -0.01925966, -0.03498315, -0.03044355,
         0.03168822,  0.04649707, -0.04399662,  0.00797387,  0.00797511,
         0.04153569, -0.04978647, -0.04925352,  0.02124642,  0.03331417,
         0.00943092,  0.04786459, -0.00975613,  0.0062451 , -0.01317055,
         0.00892959, -0.01746849, -0.00736902, -0.04779961, -0.00545485,
         0.00330795, -0.00085579]], dtype=float32)>

In [5]:
candidate_model(["001"])

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[ 0.03421209, -0.04015166,  0.02963245, -0.01593842,  0.01229014,
         0.02046939,  0.01601794, -0.03052634,  0.01199417,  0.04346177,
         0.04781044,  0.00876386,  0.02876532,  0.0186362 ,  0.00333577,
        -0.01647121, -0.03791787, -0.01912999, -0.00378069,  0.04720021,
         0.02924832,  0.03824654,  0.01725418, -0.02785802, -0.02070321,
         0.03362323, -0.02162426,  0.00551915,  0.01283291, -0.02937873,
        -0.04941409,  0.01289237]], dtype=float32)>

In [13]:
data_path = "gs://daf-vertex-poc-stg/pipelines-output/85292947717/recsys-markets-training-pipeline-20220329124524/extract-bq-to-dataset_-3790640004036820992/dataset"
data = dd.read_csv(data_path,  blocksize=25e6, dtype={"item_id": str, "user_id": int})
data.head()

user_id         item_id
0  25709672  07622300829629
1    384760  07730197002213
2  22947514  07802215303920
3  35086518  07441029556759
4   1796127  07809637200219

In [19]:
item_id = data["item_id"].unique().compute().to_list()

In [20]:
item_ds = tf.data.Dataset.from_tensor_slices(item_id)

In [21]:
item_ds

<TensorSliceDataset shapes: (), types: tf.string>

2022-04-13 12:23:27.319006: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2022-04-13 12:23:27.921480: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 96777472 exceeds 10% of free system memory.


INFO:tensorflow:Assets written to: /home/creyesp/tmp/models/model/index_bruteforce/index_model/assets


INFO:tensorflow:Assets written to: /home/creyesp/tmp/models/model/index_bruteforce/index_model/assets


In [26]:
input_path = "/home/creyesp/tmp/models/model/index_bruteforce/index_model"
bruteforce_model = tf.saved_model.load(input_path)

2022-04-13 12:25:55.474196: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 96777472 exceeds 10% of free system memory.


In [38]:
dir(bruteforce_model)
bruteforce_model.identifiers

<tf.Variable 'identifiers:0' shape=(96216,) dtype=string, numpy=
array([b'07622300829629', b'07730197002213', b'07802215303920', ...,
       b'00808829102659', b'07898591453113', b'00712221466618'],
      dtype=object)>

In [30]:
bruteforce_model([12345])


(<tf.Tensor: shape=(1, 1000), dtype=float32, numpy=
 array([[0.56777036, 0.49091446, 0.47986954, 0.44776577, 0.43891886,
         0.42341784, 0.42262372, 0.42054087, 0.41558802, 0.41339076,
         0.4129125 , 0.40916392, 0.4074785 , 0.40248635, 0.40201682,
         0.40066457, 0.39820254, 0.395388  , 0.39259243, 0.39217895,
         0.392178  , 0.3920305 , 0.39027405, 0.3887055 , 0.3886608 ,
         0.38755852, 0.38714263, 0.3863366 , 0.38633597, 0.38516158,
         0.38514104, 0.38382027, 0.38219047, 0.38109925, 0.37906778,
         0.3759378 , 0.37584147, 0.37145016, 0.3705246 , 0.36733532,
         0.36694476, 0.36575308, 0.3657518 , 0.3648607 , 0.36485827,
         0.3629811 , 0.36138844, 0.35926434, 0.3588574 , 0.358706  ,
         0.35779524, 0.35669976, 0.3560139 , 0.35567293, 0.3551811 ,
         0.35422182, 0.35288364, 0.35179007, 0.35120147, 0.35092926,
         0.34918603, 0.34898436, 0.34789813, 0.3478097 , 0.34747675,
         0.34731275, 0.34729707, 0.34697407, 0.3468

In [2]:
input_path = "../models/base_line_model/index_model/1"
input_path = "/home/creyesp/tmp/models/model/index_model/"
model = tf.saved_model.load(input_path)

FileNotFoundError: Op type not registered 'Scann>TensorsToScann' in binary running on creyesp-peya-uy. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.

## Recommend products to out of bag users (cold start problem)
<img src="https://www.researchgate.net/profile/Mehdi-Elahi-2/publication/332511384/figure/fig2/AS:749057106530306@1555600539374/Illustration-of-Cold-Start-problem-in-recommender-systems-New-user-problem-left-and.jpg" width=500>

In [7]:
score, products = model(tf.constant([21698631]))
products.numpy().tolist()

[[b'07730195010081',
  b'07730465004611',
  b'08410813214396',
  b'07730241080419',
  b'07730594004254',
  b'07730195000310',
  b'07730903270172',
  b'07730465002679',
  b'07730981310227',
  b'07509546006956',
  b'07730953460035',
  b'07730963700015',
  b'00076397030999',
  b'00787545269153',
  b'07791843016725',
  b'07730905792931',
  b'07730430002611',
  b'07896286615495',
  b'08428532210124',
  b'04015533038563',
  b'08711571019316',
  b'07730953460028',
  b'01000000001013',
  b'00000000000121',
  b'07730465001603',
  b'07736550074347',
  b'00141838104338',
  b'07730999112851',
  b'08410313325813',
  b'07730287002222',
  b'07730205072740',
  b'07730920811006',
  b'07730195002154',
  b'08410721000364',
  b'03045320523324',
  b'07730205100733',
  b'07730377008646',
  b'07740940679074',
  b'08410762002273',
  b'07730594003721',
  b'07290012983313',
  b'07730963700022',
  b'07730267009982',
  b'00000000000132',
  b'07730900850513',
  b'07730903162682',
  b'07730964340081',
  b'001906790

In [4]:
score, products = model(tf.constant([""]))
products.numpy()

array([[b'7791337002012', b'7790742172006', b'7791337000926',
        b'7791813421580', b'7790742333605', b'7790895010088',
        b'7791813421917', b'7790742172105', b'7796989075803',
        b'7791337001978']], dtype=object)

## Recommend products to existent users

In [5]:
score, products = model(tf.constant(["4655437"]))
products.numpy()

array([[b'8480017203809', b'77912268', b'7791813050520',
        b'8480017300768', b'7798130951776', b'8480017518644',
        b'8480017053480', b'8480017154057', b'8480017188274',
        b'8480017183507']], dtype=object)

In [6]:
score, products = model(tf.constant(["35417324"]))
products.numpy()

array([[b'7793046008019', b'7798061000376', b'7796490000028',
        b'7790580111533', b'7791058000731', b'7790828102095',
        b'7790022000357', b'7790383000102', b'7790070508348',
        b'7790062000584']], dtype=object)